---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Get softwawre for apt repository management.
      apt:
        name:
          - python-apt
          - python-pycurl
        state: present

    - name: Add ondrej repository for later versions of PHP.
      apt_repository: repo='ppa:ondrej/php' update_cache=yes

    - name: "Install Apache, MySQL, PHP, and other dependencies."
      apt:
        name:
          - git

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
